
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
